### ISSUE TITLE
Start of the code review process 🥸

### ISSUE THREAD

**Issue by minhnimble** [dquangit/survey#10]
Hello Quang 👋 , thank you for your effort on the code submission. I am Mikey, acting as an Engineer Lead at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process and I would love to hear back from you as well. Therefore, don’t hesitate to raise your questions or share your opinions about the implementation (if any) during the process.

If we are aligned on any issue here and you’d like to correct them, please address the issue using a proper git-flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready) and I will follow up on those fixes. Please note that you don't have to close any of my created issues after merging your PRs, I will help verify and close them for you once they pass. 😇

We expect the code review process to be completed within 2-3 days at most. As a result, ensure you are responsive during this process. If you need additional time, please inform us right away so that we can plan accordingly.

In the end, I really do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by minhnimble** [comment]
Hi, Quang 👋

I completed the 1st round of review just now. Please go ahead and provide your feedback on all the proposed issues.

Have a great day! ☀️

**Comment by minhnimble** [comment]
Good morning, Quang 👋 hope you are doing well today! 

Firstly, it is quite great to see that you have quick responses and patches on some issues I proposed yesterday, nice work there! 💪

For your information, I complete the 2nd round of review just now. Again, please go ahead and provide your feedback on all my newly proposed issues and also check some of the existing issues because I have some additional comments on them.

Have a wonderful day! ☀️

**Comment by minhnimble** [comment]
Good afternoon Quang  ☀️

As of this point, this code challenge review session reaches a conclusion and thus no more submission will be needed from your end. For the next step, you will be hearing from the Talent Acquisition team about the decision as soon as it is available. 🙏

In the end, it was a pleasure reviewing your code and getting to know you. Thanks for your time and I wish you all the best! 🍀

**Comment by dquangit** [comment]
Good afternoon Mikey, 

Thank you so much for taking the time to review my code and provide your feedback and suggestions to improve the source code quality. 
I deeply appreciate it.

Wishing you a productive week.
Best regards.
