### ISSUE TITLE
[Bug] The page indicator is not updated immediately when scrolling fast in the Survey List screen

### ISSUE THREAD

**Issue by minhnimble** [dquangit/survey#13]
## Issue

When swiping through the survey items in the Survey List screen in a quick manner, the page indicator is not updated timely and it is only changed until the users end the scrolling for a brief moment.

## Expect

The page indicator must be updated immediately and timely when users scroll quickly through the survey items in the Survey List screen.

## Step to reproduce

https://user-images.githubusercontent.com/70877098/179458776-836b688d-7e30-4a9d-a084-68a5c75ca535.MP4

**Comment by dquangit** [comment]
Fixed in #21
