### ISSUE TITLE
[Bug] The shimmer loading indicator's animation doesn't look identical to the design

### ISSUE THREAD

**Issue by minhnimble** [dquangit/survey#14]
## Issue

The application needs to show the initial shimmer loading view with animation after first entering the app with a valid logged in session. Currently, there is no proper glow animation for the loading view and it is only showing the white boxes at the text locations in Light mode, which is not matching with the design.

## Expect
- The animation for the skeleton loading view must be implemented like the following design with a correct animation that the dark glow is repeatedly transitioning from the left to the right regardless of the Light or Dark mode:

  https://user-images.githubusercontent.com/70877098/161499571-fe661524-e7b9-4763-866a-be5aa7564e91.mov

## Step to reproduce:

- Open the application with a previously logged in session:

  https://user-images.githubusercontent.com/70877098/179459292-3ec9da2a-8d79-4630-9bb0-4fd142c62c03.MP4

- The snapshot of the current shimmer loading indicator:

  <img src="https://user-images.githubusercontent.com/70877098/179474742-ea130f5e-aeb7-465d-a130-63c2a3e1c7c1.jpeg" width="300">

**Comment by dquangit** [comment]
Fixed in #25
