### ISSUE TITLE
[Bug] Starting the app without the internet connection will stuck at the skeleton loading indicator view forever

### ISSUE THREAD

**Issue by minhnimble** [dquangit/survey#16]
## Issue

When starting the application without the internet connection, if there is a previous logged session, the user will see the skeleton loading indicator view with an alert message. Unfortunately, turning the internet connection back online does nothing and the application is stuck there forever.

## Expect

When starting the application without the internet connection, if there is a previous logged session, there should be an option for the user to retry to reload the data instead of blocking the user forever with at the skeleton loading indicator view. To continue to use the application at this point, I have to restart it.

## Step to reproduce

https://user-images.githubusercontent.com/70877098/179466678-06092fa0-ed46-4b76-9f6e-4dad77b28286.mov

**Comment by dquangit** [comment]
Fixed in #33
