### ISSUE TITLE
[Bug] The skeleton loading indicator appears redundantly on the Survey List screen

### ISSUE THREAD

**Issue by minhnimble** [dquangit/survey#19]
## Issue

When starting the application with a proper internet connection and a logged session, the user will see the skeleton loading indicator view every time the application triggers to load a new page on the Survey List screen or when users scroll to the left of the first survey item.

## Expect

As per from the [design flow](https://www.figma.com/proto/GjRPOjDyZ6f4EDL3wKarRK/Challenge---Mobile-App?node-id=34%3A1450&scaling=scale-down), the skeleton must be only shown **ONE** time when first entering the Survey List screen.

## Step to reproduce

- Scroll to the left on the first survey item:

https://user-images.githubusercontent.com/70877098/179468857-493ccd9e-2112-4abb-8d69-1ccf4a74bddd.MP4

- Scroll to load the next page:

https://user-images.githubusercontent.com/70877098/179468929-0494d028-3e87-4561-8f3e-92fdf9579127.MP4

**Comment by dquangit** [comment]
Hi @minhnimble , I Survey List screen, I have used Skeleton loading as pull to refresh and load more animation. Do I need to remove them?

**Comment by minhnimble** [comment]
Hello Quang 👋, to answer your question, as per this issue's expectation, pull-to-refresh and load more actions should not use the Skeleton loading animations.

**Comment by dquangit** [comment]
Fixed in #31
