### ISSUE TITLE
[Bug] The first survey items page is duplicated when scrolling to the left on the first item in the Survey List screen

### ISSUE THREAD

**Issue by minhnimble** [dquangit/survey#26]
## Issue

When starting the application with a proper internet connection and a logged session, then in the Survey List screen, the users can scroll to the left of the first survey item. At this point, it triggers an API load and unfortunately the first survey items page gets duplicated with the redundant data of the first page.

## Expect

The survey items should not reload when scrolling to the left. Pull-to-refresh event should be trigger-able on any screen with a pull down animation instead and it should not cause duplicated contents of the first page issue.

## Step to reproduce

https://user-images.githubusercontent.com/70877098/179660936-953c6093-b55e-440d-b896-1613fbf03631.mp4

**Comment by dquangit** [comment]
Since this issue has the same root cause with #19 , so the #31 fixed the problems.
Note: The pull to refresh has not been implemented.
