### ISSUE TITLE
[Question] Refresh token logic concern

### ISSUE THREAD

**Issue by minhnimble** [dquangit/survey#29]
## Issue

Right now I notice that you trigger the refresh token logic before the application makes a request in `requestHeader` call and check if the token expires or not via the `createdAt` and `expiresIn` attributes. I am curious about why you choose to implement the refresh token logic like this approach? Then how would you solve the issue when the user alters the device's time to make the token expiry check `isExpired` always passes but the token is actually expired (server will return 401 code here) and the user is still active on the current session?
https://github.com/dquangit/survey/blob/651e93f2264711b1c81b465d8fe61e2656e182ec/Survey/Services/RestApi/AlamofireRestApi.swift#L68-L115

**Comment by dquangit** [comment]
That was my mistake, when I see `createAt` and `expiresIn` in the response, I think that we can validate an access token locally by using lifetime. But better let the server do it. Specifically for this case, I should refresh token whenever get 401 status code then retry the failed request.
